name: Hassfest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  hassfest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
